name: Every 10 Minutes Trigger

on:
  schedule:
    # Запуск каждые 10 минут
    - cron: '*/10 * * * *'
  # Позволяет запустить скрипт вручную кнопкой во вкладке Actions
  workflow_dispatch:

jobs:
  ping-website:
    runs-on: ubuntu-latest
    steps:
      - name: Open Website URL
        run: |
          curl -s -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "http://x987418r.bget.ru/index2.php"
